module.exports=(sequelize,DataTypes)=>{
    const transport= sequelize.define('transport',{
        id:{
            type:DataTypes.INTEGER,
            primaryKey:true,
            autoIncrement:true
        },
        idConducteur:{
            type:DataTypes.INTEGER
        },
        idMatricule:{
            type:DataTypes.INTEGER
        },
        adresse:{
            type:DataTypes.STRING
        },
        date:{
            type:DataTypes.STRING
        }
    },
    )
    transport.associate=function(){
        this.belongsTo(sequelize.models.conducteur,{
            foreignKey:'idConducteur'
        })
        this.belongsTo(sequelize.models.voiture,{
            foreignKey:'idMatricule'
        })
    }
    return transport
}